overrides:
- source: MAOA
  target: MSTRG.5046
  note: blastpで自動補完
- source: TPH1
  target: g8345
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.294
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.294
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.294
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.5893
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.5893
  note: blastpで自動補完
- source: TPH1
  target: g8345
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.294
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.294
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.294
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.5893
  note: blastpで自動補完
- source: TPH1
  target: MSTRG.5893
  note: blastpで自動補完
unmapped:
- source: PNMT
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
- source: COMT
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
- source: AANAT
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
- source: ASMT
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
