unmapped:
- source: TPH1
  note: BLASTで明確なオーソログ無し
- source: PNMT
  note: BLASTで明確なオーソログ無し
- source: COMT
  note: BLASTで明確なオーソログ無し
- source: AANAT
  note: BLASTで明確なオーソログ無し
- source: MAOA
  note: BLASTで明確なオーソログ無し
- source: ASMT
  note: BLASTで明確なオーソログ無し
- source: MAOA
  note: BLASTで明確なオーソログ無し
