overrides:
- source: PGK2
  target: MSTRG.5334
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8281
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8281
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8281
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8280
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8280
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8281
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8281
  note: blastpで自動補完
- source: LDHAL6B
  target: MSTRG.8282
  note: blastpで自動補完
- source: FBP2
  target: MSTRG.1711
  note: blastpで自動補完
- source: FBP2
  target: MSTRG.10591
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.7234
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1717
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1717
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1717
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1255
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.4768
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.4768
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.4768
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1259
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1259
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1392
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1392
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.9662
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3538
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3538
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1099
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.9662
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3241
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3241
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3241
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3850
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3850
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: g8192
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3851
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.174
  note: blastpで自動補完
- source: SLC2A2
  target: g9923
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3455
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3455
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3262
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3262
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3262
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8499
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.7234
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.5504
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1717
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1717
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1717
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1019
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1255
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.4768
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.4768
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.4768
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.9662
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1259
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1259
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1392
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1392
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3538
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3538
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.9662
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3261
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1099
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3850
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3850
  note: blastpで自動補完
- source: SLC2A2
  target: g8192
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8502
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3241
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3851
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3241
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3241
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1393
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3015
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3999
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.11532
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.1100
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3455
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3455
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.174
  note: blastpで自動補完
- source: SLC2A2
  target: g9923
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.8838
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3262
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3262
  note: blastpで自動補完
- source: SLC2A2
  target: MSTRG.3262
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PFKL
  target: MSTRG.2400
  note: blastpで自動補完
- source: PGAM2
  target: MSTRG.4496
  note: blastpで自動補完
- source: PCK1
  target: MSTRG.10482
  note: blastpで自動補完
- source: PCK1
  target: MSTRG.10482
  note: blastpで自動補完
- source: PCK1
  target: MSTRG.10482
  note: blastpで自動補完
- source: PCK1
  target: MSTRG.10482
  note: blastpで自動補完
unmapped:
- source: G6PC1
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
- source: HK2
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
- source: HK3
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
- source: PGI
  reason: blast_no_hit
  note: BLASTpで明確なオーソログ無し
